version: '3'
services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: 呱呱蛙
    ports:
      - "8899:80"
    environment:
      - PASSWORD=${PASSWORD:-111111}
    restart: unless-stopped
